/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ICart {
  _id?: string;
  productId: string | {
    _bsontype?: 'ObjectId';
    id?: any;
  };
  quantity: number;
  size: 'xs' | 's' | 'm' | 'l' | 'xl';
}
