/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IOrder {
  color:
    | string
    | {
        _bsontype?: "ObjectId";
        id?: any;
      };
  isReturned: boolean;
  productId:
    | string
    | {
        _bsontype?: "ObjectId";
        id?: any;
      };
  quantity: number;
  size: "xs" | "s" | "m" | "l" | "xl";
}

export interface IOrderHistory {
  cargoNumber?: string;
  orderDate: Date;
  paymentMethod: "credit-card" | "transfer" | "paypal" | "cash";
  products?: IOrder[];
  status:
    | "paymentWaiting"
    | "paymentSuccess"
    | "paymentFail"
    | "orderPrep"
    | "inCargo"
    | "delivered"
    | "error";
  statusExplanation?: string;
  stripeSecretKey: string;
  totalPrice: number;
  user?:
    | string
    | {
        _bsontype?: "ObjectId";
        id?: any;
      };
}
