/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { ICart } from '.';

export interface ILoginUser {
  email: string;
  password: string;
}

export interface IRegisterUser {
  _id?: string;
  birthDate?: Date;
  carts?: ICart[];
  email: string;
  fullName: string;
  lastLogin?: Date;
  orderHistory?: (string | {
    _bsontype?: 'ObjectId';
    id?: any;
  })[];
  password: string;
  phone?: string;
  role?: string;
  sex?: string;
}
